fridump.py: fix TypeError with recent frida versions
frida dropped support for enumerateRangesSync, which leads to the
following error at runtime:
---
Starting Memory dump...
/home/rme/builds/fridump/./fridump.py:119: DeprecationWarning: Script.exports will become asynchronous in the future, use the explicit Script.exports_sync instead
  agent = script.exports
Traceback (most recent call last):
  File "/home/rme/builds/fridump/./fridump.py", line 120, in <module>
    ranges = agent.enumerate_ranges(PERMS)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rme/builds/frida-tools/venv/lib/python3.11/site-packages/frida/core.py", line 180, in method
    return script._rpc_request(request, data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rme/builds/frida-tools/venv/lib/python3.11/site-packages/frida/core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/rme/builds/frida-tools/venv/lib/python3.11/site-packages/frida/core.py", line 497, in _rpc_request
    raise result.error
frida.core.RPCException: TypeError: not a function
    at enumerateRanges (/script1.js:5)
    at call (native)
    at handleRpcMessage (/frida/runtime/message-dispatcher.js:39)
    at handleMessage (/frida/runtime/message-dispatcher.js:25)
---

Instead, frida now uses 'Process.enumerateRanges()'. See [1] for the
current API.

It's not clear which exact commit in frida contains this change, but
the related internal frida javascript code has been updated in commit
09c8ba45de064c43fb4e20c91b2d4d0dc58edccc ("Modernize internal
JavaScript code") which is part of frida-core 16.2.1 onwards.

To fix it, switch to enumerateRanges() in fridump.

While at it, add a missing newline at the end of the file (done
automatically by text editor).

[1]: https://frida.re/docs/javascript-api/#process

Signed-off-by: Raphaël Mélotte <raphael.melotte@mind.be>